
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: your-dockerhub/user-service:latest
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /user
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /user
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
